name: Tests
on:
  push:
    branches:
      - 'master'
      - 'main'
      - 'release-'
    tags: '*'
  pull_request:
  workflow_dispatch:
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      groups: ${{ steps.set-groups.outputs.groups }}
    steps:
      - uses: actions/checkout@v6
      - name: Discover test groups
        id: set-groups
        run: |
          # Option A: derive from subdirectory names under test/
          # groups=$(ls -d test/*/  | xargs -I{} basename {} | jq -R . | jq -sc .)
          # Option B: if your groups are top-level .jl files like test/ONEBAND.jl:
          groups=$(ls test/*.jl | grep -v 'runtests.jl' | xargs -I{} basename {} .jl | jq -R . | jq -sc .)
          echo "groups=$groups" >> "$GITHUB_OUTPUT"

  test:
    needs: discover
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ matrix.group }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    permissions:
      actions: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.11'
          - '1.10' # fails with new MAK.jl version
          - 'pre'
        os:
          - ubuntu-latest
        arch:
          - x64
        group: ${{ fromJson(needs.discover.outputs.groups) }}
    env:
      GROUP: ${{ matrix.group }}
    
    steps:
      - uses: actions/checkout@v6
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v3
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1

  all-tests:
    needs: test
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Check all tests passed
        run: |
          if [[ "${{ needs.test.result }}" != "success" ]]; then
            echo "Some tests failed: ${{ needs.test.result }}"
            exit 1
          fi